language: java
jdk:
- openjdk8
branches:
  only:
  - master
cache:
  directories:
  - "$HOME/.m2"
before_install:
- cd iot001/src/main/resources-server openssl aes-256-cbc -K $encrypted_2f692484526a_key -iv $encrypted_2f692484526a_iv
  -in application.properties.enc -out application.properties -d
- openssl aes-256-cbc -K $encrypted_4ba47dcbeaaf_key -iv $encrypted_4ba47dcbeaaf_iv
  -in logback-spring.xml.enc -out logback-spring.xml -d
- cd ../../../
- chmod +x mvnw

script: ./mvnw clean package -P server

before_deploy:
- mkdir -p ./deploySrc/
-ls -al
- cp appspec.yml ./deploySrc/
- cd target
- ll
- mv iot001-1 ../deploySrc/
- cd ../deploySrc
- tar cf iotProject.tar iot001-1/ appspec.yml
- cd ../

deploy:
  - local_dir: deploySrc 
    provider: s3
    access_key_id: $AWS_ACCESS_KEY 
    secret_access_key: $AWS_SECRET_KEY  
    bucket: $S3_NAME  
    region: us-east-2
    skip_cleanup: true
    acl: private  
  
    wait-until-deployed: true

  - provider: codedeploy 
    access_key_id: $AWS_ACCESS_KEY  
    secret_access_key: $AWS_SECRET_KEY  
    bucket: $S3_NAME 
    key: iotProject.tar 
    bundle_type: tar
    application: $CodeDeployName  
    deployment_group: $CodeDeployGroupName  
    region: us-east-2
    wait-until-deployed: true