language: java
jdk:
- openjdk8
branches:
  only:
  - master
cache:
  directories:
  - "$HOME/.m2"
before_install:
- cd iot001/src/main/resources-server
- openssl aes-256-cbc -K $encrypted_bedc26df5945_key -iv $encrypted_bedc26df5945_iv -in property.tar.enc -out property.tar -d
- tar xf property.tar
- cd ../../../
- chmod +x mvnw
script: "./mvnw clean package -P server"
before_deploy:
- cp appspec.yml target/iot001-1/
- cp deploy.txt target/iot001-1/deploy.sh
- ls al

deploy:
- local_dir: target/iot001-1/
  provider: s3
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
  bucket: "$S3_NAME"
  region: us-east-2
  skip_cleanup: true
  acl: private
  wait-until-deployed: true
- provider: codedeploy
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
  bucket: "$S3_NAME"
  key: iotProject.tar
  bundle_type: tar
  application: "$CodeDeployName"
  deployment_group: "$CodeDeployGroupName"
  region: us-east-2
  wait-until-deployed: true
