language: java
jdk:
  - openjdk8

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.m2

script: 
  - iot001/mvnw clean package

before_install:
  - chmod +x iot001/mvnw
# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - yhs241@gmail.com
