language: java
jdk:
  - openjdk8

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.m2
 

before_install:
  - chmod +x mvnw
# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - yhs241@gmail.com
