language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 $Home(어느 폴더지?travis 상의 폴더인가)
cache:
  directories:
    - '$HOME/.m2/repository'

script: "./mvn package"

 
# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - yhs3307@hanmail.net