version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ec2-user/app/step3/zip/
    overwrite: yes
    
permissions:
  - object: / #모든 파일에 아래 권한 부여
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStart: #배포시 이 단계에서 아래 스크립트를 아래 권한자로 실행. 60초동안 안되면 실패
    - location: deploy.sh
      timeout: 60
      runas: ec2-user